### ISSUE TITLE
[OLLVM代码混淆移植与使用] 结构有些乱，建议优化

### ISSUE THREAD

**Issue by zhenian** [heroims/heroims.github.io#1]
[OLLVM代码混淆移植与使用] 结构有些乱，建议优化

没办法 step by step 使用

https://heroims.github.io/2019/01/06/OLLVM%E4%BB%A3%E7%A0%81%E6%B7%B7%E6%B7%86%E7%A7%BB%E6%A4%8D%E4%B8%8E%E4%BD%BF%E7%94%A8/

**Comment by heroims** [comment]
1
